name: Build and Deploy Node.js App to Azure Web App - hpcc-ecl-web-editor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --no-cache

      - name: Build React app
        run: npm run build

      - name: Archive artifact for deployment
        run: zip -r release.zip . -x "node_modules/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Install production dependencies
        run: npm install --production

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "hpcc-ecl-web-editor"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B99994A4E7084E05979E85CA3ED32AD8 }}
          package: .
